language: c
os: linux
dist: bionic

jobs:
  include:
  - env: BUILD_FOR_ARCH=i386
    before_install:
    - sudo apt-get -y install gcc-multilib
  - env: BUILD_FOR_ARCH=riscv
    before_install:
    - sudo apt-get -y install gcc-riscv64-linux-gnu libc6-dev-riscv64-cross u-boot-tools

script:
- make ARCH=$BUILD_FOR_ARCH
